#
# Theme Settings via Powerlevel9k (https://github.com/bhilburn/powerlevel9k)
#

# Fonts
# Note that use Cica (https://github.com/miiton/Cica) in iTerm.
POWERLEVEL9K_MODE="awesome-fontconfig"

# Prompt layouts
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_RPROMPT_ON_NEWLINE=true
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=""

# Prompt elements
POWERLEVEL9K_OS_ICON_FOREGROUND="240"
POWERLEVEL9K_OS_ICON_BACKGROUND="253"

POWERLEVEL9K_HOST_TEMPLATE="%n@%1m"
POWERLEVEL9K_HOST_ICON="\uF109 "
POWERLEVEL9K_SSH_ICON="\uF489 "
POWERLEVEL9K_HOST_LOCAL_FOREGROUND="189"
POWERLEVEL9K_HOST_LOCAL_BACKGROUND="060"
POWERLEVEL9K_HOST_REMOTE_FOREGROUND="231"
POWERLEVEL9K_HOST_REMOTE_BACKGROUND="060"

POWERLEVEL9K_DIR_HOME_FOREGROUND="060"
POWERLEVEL9K_DIR_HOME_BACKGROUND="189"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="060"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND="189"
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="060"
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND="189"
POWERLEVEL9K_DIR_ETC_FOREGROUND="060"
POWERLEVEL9K_DIR_ETC_BACKGROUND="189"
POWERLEVEL9K_HOME_ICON="\uF015 "
POWERLEVEL9K_HOME_SUB_ICON="\uF07C "
POWERLEVEL9K_FOLDER_ICON="\uF07B "
POWERLEVEL9K_ETC_ICON="\uF013 "

POWERLEVEL9K_VCS_CLEAN_FOREGROUND="061"
POWERLEVEL9K_VCS_CLEAN_BACKGROUND="152"
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND="202"
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND="229"
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND="161"
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND="224"

POWERLEVEL9K_PYENV_PROMPT_ALWAYS_SHOW=true
POWERLEVEL9K_PYTHON_ICON="\uE73C"
POWERLEVEL9K_PYENV_FOREGROUND="052"
POWERLEVEL9K_PYENV_BACKGROUND="181"

POWERLEVEL9K_TIME_FOREGROUND="240"
POWERLEVEL9K_TIME_BACKGROUND="253"

zsh_is_docker() {
    if [ -f "/.dockerenv" ]; then
        echo -n "\uE7B0 "
    fi
}
POWERLEVEL9K_CUSTOM_IS_DOCKER="zsh_is_docker"
POWERLEVEL9K_CUSTOM_IS_DOCKER_FOREGROUND="233"
POWERLEVEL9K_CUSTOM_IS_DOCKER_BACKGROUND="231"

# Prompt
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=("os_icon" "custom_is_docker" "host" "dir" "vcs")
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=("pyenv" "time")

zplug "bhilburn/powerlevel9k", use:powerlevel9k.zsh-theme
